#txt file generated by Color Shades Lab
meta_file_path = r"E:\0image\33\33.txt"

#RP port name
pi_port_name = "COM6"

# MQTT configuration
broker = "172.27.172.180"
port = 1883
keep_alive = 60


def get_meta_file_path():
    return meta_file_path

def get_port_name():
    return pi_port_name

def get_MQTTconfiguration():
    return broker, port, keep_alive